import { READINESS_TEMPLATES, TEMPLATE_VERSION } from "./readiness-templates";

/** Renders docs/READINESS-INSTRUMENT.md from the shipped templates, so the review copy cannot drift. */
export function renderReviewDoc(): string {
  const [base, ...variants] = READINESS_TEMPLATES;
  const lines: string[] = [
    "# Readiness instrument — items for review",
    "",
    "> Generated by `pnpm instruments:doc` from `lib/instruments/readiness-templates.ts`. Edit the",
    "> templates, not this file; a unit test fails if the two differ.",
    "",
    `Template version ${TEMPLATE_VERSION}. **Status: draft, awaiting the product owner's review.**`,
    "",
    "## What these are",
    "",
    "Trestle's own wording. Each item operationalises a construct from the readiness literature in",
    "`RESEARCH.md` §2 and the ERP critical-success-factor studies in §1.2; the source column names the",
    "construct, not a copied item. No published scale's item text is reproduced.",
    "",
    "Before the capstone uses them as a measure, they need the content-validity step in `RESEARCH.md`",
    "§6.3(c): an expert panel rates each item's relevance (CVI), then Cronbach's alpha on pilot data.",
    "",
    "Scale: 5-point agreement (Strongly disagree … Strongly agree). Items marked **R** are",
    "reverse-worded and reverse-scored; they also catch straight-lining.",
    "",
    "## Dimensions",
    "",
    "| Dimension | Weight |",
    "|---|---|",
    ...base!.definition.dimensions.map((d) => `| ${d.name} | ${d.weight} |`),
    "",
    "## The default instrument",
    "",
  ];
  const dimName = new Map(base!.definition.dimensions.map((d) => [d.key, d.name]));
  let n = 0;
  for (const s of base!.definition.sections) {
    lines.push(`### ${s.title}`, "", s.description ?? "", "", "| # | Item | Dimension | R | Construct and source |", "|---|---|---|---|---|");
    for (const q of s.questions) {
      n += 1;
      lines.push(
        `| ${n} | ${q.text} | ${q.dimension ? dimName.get(q.dimension) : "Open text"} | ${q.reverse ? "R" : ""} | ${q.source ?? "—"} |`,
      );
    }
    lines.push("");
  }
  lines.push(
    "## Per engagement type",
    "",
    "Each type uses the items above with the change named for that type, plus one item of its own.",
    "",
    "| Template | The change is called | Extra item | Dimension | Source |",
    "|---|---|---|---|---|",
  );
  for (const v of variants) {
    const x = v.wording.specific;
    lines.push(`| ${v.name} | ${v.wording.change} | ${x?.text ?? "—"} | ${x ? dimName.get(x.dimension) : "—"} | ${x?.source ?? "—"} |`);
  }
  lines.push(
    "",
    "## Open questions for review",
    "",
    "1. **Personal valence** (\"what happens to me?\") has no dimension. `RESEARCH.md` §2.5 and §8 item 1",
    "   lean towards adding it as a seventh dimension; it is the belief that most directly predicts",
    "   individual resistance, and it matters most for automation engagements.",
    "2. **Business process readiness** is in the ODTR framework (`POSITIONING.md` §5.2) but not here.",
    "3. Wording is international English; check it reads naturally to the first clients' staff.",
    "",
  );
  return lines.join("\n");
}
